language: java
 
os:
  - linux

jdk:
  - oraclejdk8
  - openjdk8
 
script: "mvn cobertura:cobertura"
   
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1b8eeb10-0986-4df3-9ed3-d7c15ccda621
